/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hospital;

import Doctor.Doctor;
import Login.Login;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author 25470
 */
public class Hospital extends javax.swing.JFrame {
private JFrame frame;
    /**
     * Creates new form Hospital
     */
    public Hospital() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtPrescription = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jbtnUpdate = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnDoctor = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jbtnPayment = new javax.swing.JButton();
        jbtnPharmacyoffice = new javax.swing.JButton();
        jbtnLogin = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jcmbNameTablets = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jtxtNumberTablets = new javax.swing.JTextField();
        jtxtRef = new javax.swing.JTextField();
        jtxtDose = new javax.swing.JTextField();
        jtxtLot = new javax.swing.JTextField();
        jtxtIssuedDate = new javax.swing.JTextField();
        jtxtExpDate = new javax.swing.JTextField();
        jtxtDailyDose = new javax.swing.JTextField();
        jtxtPossibleSideEffects = new javax.swing.JTextField();
        jtxtFurtherInformation = new javax.swing.JTextField();
        jtxtStorageAdvice = new javax.swing.JTextField();
        jtxtDrivingUsingMachines = new javax.swing.JTextField();
        jtxtHowtoUseMedication = new javax.swing.JTextField();
        jtxtPatientID = new javax.swing.JTextField();
        jtxtDoctorNHSNo = new javax.swing.JTextField();
        jtxtAdministration = new javax.swing.JTextField();
        jtxtPatientName = new javax.swing.JTextField();
        jtxtAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1350, 700));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1350, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel1.setText("Hospital Management Systems");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1310, 70));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtPrescription.setColumns(20);
        jtxtPrescription.setRows(5);
        jScrollPane1.setViewportView(jtxtPrescription);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 360, 410));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 80, 370, 410));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Patient Prescription");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 940, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnUpdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, -1));

        jbtnDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 130, -1));

        jbtnDoctor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnDoctor.setText("Doctor");
        jbtnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDoctorActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 140, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("GP Appointment");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 170, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("Patient");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 110, -1));

        jbtnPayment.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnPayment.setText("Reset");
        jbtnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPaymentActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 120, -1));

        jbtnPharmacyoffice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnPharmacyoffice.setText("Prescription");
        jbtnPharmacyoffice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPharmacyofficeActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnPharmacyoffice, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 130, -1));

        jbtnLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnLogin.setText("Login");
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 140, -1));

        jbtnPrint.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, 140, -1));

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton10.setText("Exit");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 10, 90, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 1310, 50));

        jcmbNameTablets.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcmbNameTablets.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make a Selection", "Ibuprofen", "Co-codamol", "Paracetamol", "Amlodipine" }));
        jcmbNameTablets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbNameTabletsActionPerformed(evt);
            }
        });
        getContentPane().add(jcmbNameTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Name of Tablets");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jtxtNumberTablets.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtNumberTablets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNumberTabletsActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtNumberTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 190, -1));

        jtxtRef.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 190, -1));

        jtxtDose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 190, -1));

        jtxtLot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtLot, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 190, -1));

        jtxtIssuedDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtIssuedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 190, -1));

        jtxtExpDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtExpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 190, -1));

        jtxtDailyDose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtDailyDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 190, -1));

        jtxtPossibleSideEffects.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtPossibleSideEffects, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 190, -1));

        jtxtFurtherInformation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtFurtherInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 220, -1));

        jtxtStorageAdvice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtStorageAdvice, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 220, -1));

        jtxtDrivingUsingMachines.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtDrivingUsingMachines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDrivingUsingMachinesActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtDrivingUsingMachines, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, 220, -1));

        jtxtHowtoUseMedication.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtHowtoUseMedication, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 220, -1));

        jtxtPatientID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtPatientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPatientIDActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, 220, -1));

        jtxtDoctorNHSNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtDoctorNHSNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 220, -1));

        jtxtAdministration.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtAdministration, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, 220, -1));

        jtxtPatientName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPatientNameActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, 220, -1));

        jtxtAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAddressActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 450, 220, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Reference No.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 170, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Dose (Mg):");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Number of Tablets:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("LOT:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Issued Date:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Exp Date:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Daily Dose:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Possible Side Effects:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Further Information:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Storage Advice:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Driving and Using Machines");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("How to Use Medicine:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Patient ID:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("NHS Number:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Patient Name:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Date of Birth:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Patient Address:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name of Tablets", "Reference No.", "Dose (mg)", "Number of Tablets", "LOT", "Issued Date", "Daily Dose", "Daily Dose", "Possible Side Effects", "Further Information", "Storage Advice", "Driving and using Medication", "How to Use Medication", "Patient ID", "NHS Number", "Patient Name", "Date of Birth", "Patient Address"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 1310, 130));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtNumberTabletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNumberTabletsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNumberTabletsActionPerformed

    private void jtxtPatientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPatientIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPatientIDActionPerformed

    private void jtxtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAddressActionPerformed

    private void jtxtDrivingUsingMachinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDrivingUsingMachinesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDrivingUsingMachinesActionPerformed

    private void jtxtPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPatientNameActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jbtnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPaymentActionPerformed
        jtxtRef.setText("");
        jtxtDose.setText("");
        jtxtNumberTablets.setText("");
        jtxtLot.setText("");
        jtxtIssuedDate.setText("");
        jtxtExpDate.setText("");
        jtxtDailyDose.setText("");
        
        jtxtPossibleSideEffects.setText("");
        jtxtFurtherInformation.setText("");
        jtxtStorageAdvice.setText("");
        jtxtDrivingUsingMachines.setText("");
        jtxtHowtoUseMedication.setText("");
        jtxtPatientID.setText("");
        jtxtDoctorNHSNo.setText("");
        jtxtPatientName.setText("");
        jtxtAddress.setText("");
        jtxtAdministration.setText("");
        jcmbNameTablets.getModel().setSelectedItem("Make a Selection");
    }//GEN-LAST:event_jbtnPaymentActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    
    if(jTable1.getSelectedRow()==-1){
        if(jTable1.getRowCount()==0){
            JOptionPane.showMessageDialog(null, "No data to delete","Hospital Management Systems",
                    JOptionPane.OK_OPTION);
        }else{
            JOptionPane.showMessageDialog(null, "Select a row to delete","Hospital Management Systems",
            JOptionPane.OK_OPTION);
        }
        }else{
                model.removeRow(jTable1.getSelectedRow());
                }
    
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
frame = new JFrame();
if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Hospital Management Systems",
        JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
    System.exit(0);
}
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
try{
    jtxtPrescription.print();
}catch (PrinterException ex){
    Logger.getLogger(Hospital.class.getName()).log(Level.SEVERE,null,ex);
}
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jcmbNameTabletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbNameTabletsActionPerformed
    if (jcmbNameTablets.getSelectedItem().equals("Ibuprofen"))
    {
        jtxtRef.setText("Ibu8568959");
        jtxtDose.setText("2");
        jtxtNumberTablets.setText("32");
        jtxtLot.setText("561005875");
        jtxtIssuedDate.setText("06/05/2018");
        jtxtExpDate.setText("04/05/2019");
        jtxtDailyDose.setText("4");
        
        jtxtPossibleSideEffects.setText("Bleeding");
        jtxtFurtherInformation.setText("Place Dispensary");
        jtxtStorageAdvice.setText("Less than 20%");
        jtxtDrivingUsingMachines.setText("No");
        jtxtHowtoUseMedication.setText("use Water,No Alcohol");
        jtxtPatientID.setText("P9589454");
        jtxtDoctorNHSNo.setText("646564");
    }
    else if (jcmbNameTablets.getSelectedItem().equals("Co-codamol"))
    {
        jtxtRef.setText("COCO6758940");
        jtxtDose.setText("500");
        jtxtNumberTablets.setText("30");
        jtxtLot.setText("B770034");
        jtxtIssuedDate.setText("06/05/2018");
        jtxtExpDate.setText("04/05/2019");
        jtxtDailyDose.setText("2");
        
        jtxtPossibleSideEffects.setText("Dizziness");
        jtxtFurtherInformation.setText("Place Dispensary");
        jtxtStorageAdvice.setText("Less than 20%");
        jtxtDrivingUsingMachines.setText("No");
        jtxtHowtoUseMedication.setText("use Water,No Alcohol");
        jtxtPatientID.setText("P9589454");
        jtxtDoctorNHSNo.setText("646564");
    }
    else if (jcmbNameTablets.getSelectedItem().equals("Paracetamol"))
    {
        jtxtRef.setText("01729214");
        jtxtDose.setText("500");
        jtxtNumberTablets.setText("16");
        jtxtLot.setText("0204324");
        jtxtIssuedDate.setText("07/05/2018");
        jtxtExpDate.setText("04/05/2023");
        jtxtDailyDose.setText("2");
        
        jtxtPossibleSideEffects.setText("Feeling Sick");
        jtxtFurtherInformation.setText("Place Dispensary");
        jtxtStorageAdvice.setText("Less than 25%");
        jtxtDrivingUsingMachines.setText("No");
        jtxtHowtoUseMedication.setText("use Water,No Alcohol");
        jtxtPatientID.setText("P5562454");
        jtxtDoctorNHSNo.setText("875564");
    }
    else if (jcmbNameTablets.getSelectedItem().equals("Amlodipine"))
    {
        jtxtRef.setText("Am05875");
        jtxtDose.setText("5");
        jtxtNumberTablets.setText("28");
        jtxtLot.setText("8745475");
        jtxtIssuedDate.setText("06/05/2018");
        jtxtExpDate.setText("04/05/2020");
        jtxtDailyDose.setText("1");
        
        jtxtPossibleSideEffects.setText("Liver Disease");
        jtxtFurtherInformation.setText("Ability to drive may be affected");
        jtxtStorageAdvice.setText("No special storage");
        jtxtDrivingUsingMachines.setText("No");
        jtxtHowtoUseMedication.setText("use Water,No Alcohol");
        jtxtPatientID.setText("P9129454");
        jtxtDoctorNHSNo.setText("6346564");
    }
    else if (jcmbNameTablets.getSelectedItem().equals("Make a Selection"))
    {
        jtxtRef.setText("");
        jtxtDose.setText("");
        jtxtNumberTablets.setText("");
        jtxtLot.setText("");
        jtxtIssuedDate.setText("");
        jtxtExpDate.setText("");
        jtxtDailyDose.setText("");
        
        jtxtPossibleSideEffects.setText("");
        jtxtFurtherInformation.setText("");
        jtxtStorageAdvice.setText("");
        jtxtDrivingUsingMachines.setText("");
        jtxtHowtoUseMedication.setText("");
        jtxtPatientID.setText("");
        jtxtDoctorNHSNo.setText("");
    }
    }//GEN-LAST:event_jcmbNameTabletsActionPerformed

    private void jbtnPharmacyofficeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPharmacyofficeActionPerformed
     String Qty1 = (jtxtRef.getText());
     String Qty2 = (jtxtNumberTablets.getText());
     String Qty3 = (jtxtLot.getText());
     String Qty4 = (jtxtDailyDose.getText());
     String Qty5 = (jtxtPossibleSideEffects.getText());
     String Qty6 = (jtxtFurtherInformation.getText());
     String Qty7 = (jtxtPossibleSideEffects.getText());
     String Qty8 = (jtxtHowtoUseMedication.getText());
     String Qty9 = (jtxtPatientID.getText());
     String Qty10 = (jtxtPatientName.getText());
     String Qty11 = (jtxtAdministration.getText());
     String Qty12 = (jtxtAddress.getText());
     String Qty13 = "";
     
     if(jcmbNameTablets.getSelectedItem().equals("Ibuprofen")){
         Qty13 = "Ibuprofen";
     }
     else if(jcmbNameTablets.getSelectedItem().equals("Co-codamol")){
         Qty13 = "Co-codamol";
     }
     else if(jcmbNameTablets.getSelectedItem().equals("Paracetamol")){
         Qty13 = "Paracetamol";
     }
     else if(jcmbNameTablets.getSelectedItem().equals("Amlodipine")){
         Qty13 = "Amlodipine";
     }
     
     
     jtxtPrescription.setText("");
     jtxtPrescription.append("\t\n\tHospital Management Systems\n"
     +"\nPatient Name:\t\t" + Qty10
     +"\nDate of Birth:\t\t" + Qty11
     +"\nPatient Address:\t" + Qty12
     +"\nPrescription:\t\t" + Qty13
     +"\nReference No:\t\t" + Qty1
     +"\nDose (mg):\t\t" + Qty2
     +"\nNumber of Tablets:\t" + Qty3
     +"\nLOT:\t\t" + Qty4
     +"\nDaily Dose:\t\t" + Qty5
     +"\nPossible Side Effects:\t" + Qty6
     +"\nFurther Information:\t" + Qty7
     +"\nHow to Use Medication:\t" + Qty8
     +"\nPatient ID:\t\t" + Qty9
     +"\n\n\tPatient Instruction we have introduced a \n\tfree text confirmation\n\t"
     +"TEXT REMINDERS FOR APPOINTMENT");
    }//GEN-LAST:event_jbtnPharmacyofficeActionPerformed

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
      Login iLogin = new Login();
      iLogin.setVisible(true);
      dispose();
    }//GEN-LAST:event_jbtnLoginActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.addRow(new Object[]{jcmbNameTablets.getSelectedItem().toString(),jtxtRef.getText(),
    jtxtDose.getText(),jtxtNumberTablets.getText(),jtxtLot.getText(),jtxtIssuedDate.getText(),jtxtExpDate.getText(),
    jtxtDailyDose.getText(),jtxtPossibleSideEffects.getText(),jtxtFurtherInformation.getText(),jtxtStorageAdvice.getText(),
    jtxtDrivingUsingMachines.getText(),jtxtHowtoUseMedication.getText(),jtxtPatientID.getText(),jtxtDoctorNHSNo.getText(),
    jtxtPatientName.getText(),jtxtAdministration.getText(),jtxtAddress.getText(),});
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDoctorActionPerformed
      Doctor iDoctor = new Doctor();
      iDoctor.setVisible(true);
      dispose();
    }//GEN-LAST:event_jbtnDoctorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hospital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnDoctor;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnPayment;
    private javax.swing.JButton jbtnPharmacyoffice;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JComboBox<String> jcmbNameTablets;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtAdministration;
    private javax.swing.JTextField jtxtDailyDose;
    private javax.swing.JTextField jtxtDoctorNHSNo;
    private javax.swing.JTextField jtxtDose;
    private javax.swing.JTextField jtxtDrivingUsingMachines;
    private javax.swing.JTextField jtxtExpDate;
    private javax.swing.JTextField jtxtFurtherInformation;
    private javax.swing.JTextField jtxtHowtoUseMedication;
    private javax.swing.JTextField jtxtIssuedDate;
    private javax.swing.JTextField jtxtLot;
    private javax.swing.JTextField jtxtNumberTablets;
    private javax.swing.JTextField jtxtPatientID;
    private javax.swing.JTextField jtxtPatientName;
    private javax.swing.JTextField jtxtPossibleSideEffects;
    private javax.swing.JTextArea jtxtPrescription;
    private javax.swing.JTextField jtxtRef;
    private javax.swing.JTextField jtxtStorageAdvice;
    // End of variables declaration//GEN-END:variables
}
