/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Doctor;

import Hospital.Hospital;
import Login.Login;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 25470
 */
public class Doctor extends javax.swing.JFrame {
private JFrame frame;
    /**
     * Creates new form Doctor
     */
    public Doctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtPrescription = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jbtnUpdate = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnHospital = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnPharmacyoffice = new javax.swing.JButton();
        jbtnLogin = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jtnExit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtxtSurname = new javax.swing.JTextField();
        jtxtDoctorNHS = new javax.swing.JTextField();
        jtxtFirstname = new javax.swing.JTextField();
        jtxtMedicalCentreName = new javax.swing.JTextField();
        jtxtPatient = new javax.swing.JTextField();
        jtxtAddressCentre = new javax.swing.JTextField();
        jtxtPostCode = new javax.swing.JTextField();
        jtxtMedicalCentreRef = new javax.swing.JTextField();
        jtxtOffice1 = new javax.swing.JTextField();
        jtxtOffice2 = new javax.swing.JTextField();
        jtxtFaxNo = new javax.swing.JTextField();
        jtxtEmailAddress = new javax.swing.JTextField();
        jtxtPatientNHS = new javax.swing.JTextField();
        jtxtGp = new javax.swing.JTextField();
        jtxtEMIS = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jcmbNameTablets = new javax.swing.JComboBox<>();
        jcmbDoctorRef = new javax.swing.JComboBox<>();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1350, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtPrescription.setColumns(20);
        jtxtPrescription.setRows(5);
        jScrollPane1.setViewportView(jtxtPrescription);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 360, 410));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 370, 410));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnUpdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, -1));

        jbtnDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 130, -1));

        jbtnHospital.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnHospital.setText("Hospital");
        jbtnHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHospitalActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 140, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("GP Appointment");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 170, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("Patient");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 110, -1));

        jbtnReset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 120, -1));

        jbtnPharmacyoffice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnPharmacyoffice.setText("Prescription");
        jbtnPharmacyoffice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPharmacyofficeActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnPharmacyoffice, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 160, -1));

        jbtnLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnLogin.setText("Login");
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 110, -1));

        jbtnPrint.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, 140, -1));

        jtnExit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtnExit.setText("Exit");
        jtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtnExitActionPerformed(evt);
            }
        });
        jPanel4.add(jtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 10, 90, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 1310, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Doctor's Ref No");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jtxtSurname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSurnameActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 190, -1));

        jtxtDoctorNHS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtDoctorNHS, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 190, -1));

        jtxtFirstname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 190, -1));

        jtxtMedicalCentreName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtMedicalCentreName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 190, -1));

        jtxtPatient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 190, -1));

        jtxtAddressCentre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtAddressCentre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 190, -1));

        jtxtPostCode.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtPostCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 190, -1));

        jtxtMedicalCentreRef.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtMedicalCentreRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 220, -1));

        jtxtOffice1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtOffice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 220, -1));

        jtxtOffice2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtOffice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtOffice2ActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtOffice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 220, -1));

        jtxtFaxNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtFaxNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 220, -1));

        jtxtEmailAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEmailAddressActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtEmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, 220, -1));

        jtxtPatientNHS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtPatientNHS, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 220, -1));

        jtxtGp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtGp, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 220, -1));

        jtxtEMIS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtEMIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEMISActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtEMIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, 220, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Doctor NHS No");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 170, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Firstname");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Surname");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Medical Centre Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Patient ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Address of Centre");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Post Code");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Medical Centre Ref");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Office Phone No 1");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Office Phone No 2");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Fax No");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Email Address");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Patient NHS Number");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("EMIS Number");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Gp Appointment Ref");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor's Ref No", "Doctor NHS No", "Firstname", "Surname", "Medical Centre Name", "Patient ID", "Address of Centre", "Post Code", "Medical Centre Ref", "Office Phone No 1", "Office Phone No 2", "Fax No", "Email Address", "Patient NHS Number", "EMIS Number", "Gp Appointment"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 1310, 210));

        jcmbNameTablets.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcmbNameTablets.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make a Selection", "Ibuprofen", "Co-codamol", "Paracetamol", "Amlodipine" }));
        jcmbNameTablets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbNameTabletsActionPerformed(evt);
            }
        });
        getContentPane().add(jcmbNameTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jcmbDoctorRef.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcmbDoctorRef.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Doctor's Ref No", "QE2945", "JK30036", "DC56108", "PM11362", "BQ01968" }));
        jcmbDoctorRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbDoctorRefActionPerformed(evt);
            }
        });
        getContentPane().add(jcmbDoctorRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 190, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{jcmbDoctorRef.getSelectedItem().toString(),jtxtDoctorNHS.getText(),
            jtxtFirstname.getText(),jtxtSurname.getText(),jtxtMedicalCentreName.getText(),jtxtPatient.getText(),jtxtAddressCentre.getText(),
            jtxtPostCode.getText(),jtxtMedicalCentreRef.getText(),jtxtOffice1.getText(),
            jtxtOffice2.getText(),jtxtFaxNo.getText(),jtxtEmailAddress.getText(),jtxtPatientNHS.getText(),
            jtxtEMIS.getText(),jtxtGp.getText(),});
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        if(jTable1.getSelectedRow()==-1){
            if(jTable1.getRowCount()==0){
                JOptionPane.showMessageDialog(null, "No data to delete","Hospital Management Systems",
                    JOptionPane.OK_OPTION);
            }else{
                JOptionPane.showMessageDialog(null, "Select a row to delete","Hospital Management Systems",
                    JOptionPane.OK_OPTION);
            }
        }else{
            model.removeRow(jTable1.getSelectedRow());
        }

    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        jtxtDoctorNHS.setText("");
        jtxtFirstname.setText("");
        jtxtSurname.setText("");
        jtxtMedicalCentreName.setText("");
        jtxtPatient.setText("");
        jtxtAddressCentre.setText("");
        jtxtPostCode.setText("");

        jtxtMedicalCentreRef.setText("");
        jtxtOffice1.setText("");
        jtxtOffice2.setText("");
        jtxtFaxNo.setText("");
        jtxtEmailAddress.setText("");
        jtxtPatientNHS.setText("");
        jtxtEMIS.setText("");
        jtxtGp.setText("");
        jcmbDoctorRef.getModel().setSelectedItem("Select Doctor's Ref No");
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnPharmacyofficeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPharmacyofficeActionPerformed

        String Qty2 = (jtxtDoctorNHS.getText());
        String Qty3 = (jtxtFirstname.getText());
        String Qty4 = (jtxtSurname.getText());
        String Qty5 = (jtxtMedicalCentreName.getText());
        String Qty6 = (jtxtMedicalCentreRef.getText());
        String Qty7 = (jtxtPatient.getText());
        String Qty8 = (jtxtPatientNHS.getText());
        String Qty9 = (jtxtEMIS.getText());
        String Qty10 = (jtxtOffice1.getText());
        String Qty11 = (jtxtOffice2.getText());
        String Qty12 = "";
     
     if(jcmbDoctorRef.getSelectedItem().equals("QE29845")){
         Qty12 = "QE29845";
     }
     else if(jcmbDoctorRef.getSelectedItem().equals("JK30036")){
         Qty12 = "JK30036";
     }
     else if(jcmbDoctorRef.getSelectedItem().equals("PM11362")){
         Qty12 = "PM11362";
     }
     else if(jcmbDoctorRef.getSelectedItem().equals("BQ01968")){
         Qty12 = "BQ01968";
     }

        jtxtPrescription.setText("");
        jtxtPrescription.append("\t\n\tHospital Management Systems\n"
            +"\nDoctor's Ref No:\t" + Qty12
            +"\nDoctors NHS NO:\t" + Qty2
            +"\nFirstname:\t\t" + Qty3
            +"\nSurname:\t\t" + Qty4
            +"\nMedical Centre Name:\t" + Qty5
            +"\nMedical Centre Ref:\t" + Qty6
            +"\nPatient ID:\t\t" + Qty7
            +"\nPatient NHS Number:\t" + Qty8
            +"\nEMIS Number:\t\t" + Qty9
            +"\nOffice Phone No 1:\t" + Qty10
            +"\nOffice Phone No 2:\t" + Qty11
            +"\n\n\tPatient Instruction we have introduced a \n\tfree text confirmation\n\t"
            +"TEXT REMINDERS FOR APPOINTMENT");
    }//GEN-LAST:event_jbtnPharmacyofficeActionPerformed

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        Login iLogin = new Login();
        iLogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtnLoginActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        try{
            jtxtPrescription.print();
        }catch (PrinterException ex){
            Logger.getLogger(Hospital.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtnExitActionPerformed
        frame = new JFrame();
        if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Hospital Management Systems",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
        System.exit(0);
        }
    }//GEN-LAST:event_jtnExitActionPerformed

    private void jtxtSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSurnameActionPerformed

    private void jtxtOffice2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtOffice2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtOffice2ActionPerformed

    private void jtxtEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEmailAddressActionPerformed

    private void jtxtEMISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEMISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEMISActionPerformed

    private void jbtnHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHospitalActionPerformed
     Hospital iHospital = new Hospital();
     iHospital.setVisible(true);
     dispose();
    }//GEN-LAST:event_jbtnHospitalActionPerformed

    private void jcmbNameTabletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbNameTabletsActionPerformed
       
    }//GEN-LAST:event_jcmbNameTabletsActionPerformed

    private void jcmbDoctorRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbDoctorRefActionPerformed
 if (jcmbDoctorRef.getSelectedItem().equals("QE29845"))
        {
            jtxtDoctorNHS.setText("DrNHS5968");
            jtxtFirstname.setText("Nancy");
            jtxtSurname.setText("Joan");
            jtxtMedicalCentreName.setText("Deryk Cheed Medical Centre");
            jtxtPatient.setText("34290887");
            jtxtAddressCentre.setText("10 Roadwork Lane");
            jtxtPostCode.setText("908100");

            jtxtMedicalCentreRef.setText("MCR68945");
            jtxtOffice1.setText("0702455345");
            jtxtOffice2.setText("0702455555");
            jtxtFaxNo.setText("0702455567");
            jtxtEmailAddress.setText("nancyjoan@gmail.com");
            jtxtPatientNHS.setText("6754328");
            jtxtEMIS.setText("646564");
            jtxtGp.setText("Yes");
        }
        else if (jcmbDoctorRef.getSelectedItem().equals("JK30036"))
        {
            jtxtDoctorNHS.setText("DrNHS6753");
            jtxtFirstname.setText("John");
            jtxtSurname.setText("Michael");
            jtxtMedicalCentreName.setText("Deryk Cheed Medical Centre");
            jtxtPatient.setText("786439");
            jtxtAddressCentre.setText("10 Roadwork Lane");
            jtxtPostCode.setText("908100");

            jtxtMedicalCentreRef.setText("MCR68945");
            jtxtOffice1.setText("0702563255");
            jtxtOffice2.setText("0702564355");
            jtxtFaxNo.setText("0702564237");
            jtxtEmailAddress.setText("johnmichael@gmail.com");
            jtxtPatientNHS.setText("78589454");
            jtxtEMIS.setText("646564");
            jtxtGp.setText("Yes");
        }
        else if (jcmbDoctorRef.getSelectedItem().equals("DC56108"))
        {
            jtxtDoctorNHS.setText("DrNHS8078");
            jtxtFirstname.setText("Esha");
            jtxtSurname.setText("Remmy");
            jtxtMedicalCentreName.setText("Deryk Cheed Medical Centre");
            jtxtPatient.setText("7854329");
            jtxtAddressCentre.setText("10 Roadwork Lane");
            jtxtPostCode.setText("908100");

            jtxtMedicalCentreRef.setText("MCR68945");
            jtxtOffice1.setText("0703567896");
            jtxtOffice2.setText("0703566897");
            jtxtFaxNo.setText("0703565458");
            jtxtEmailAddress.setText("esharemmy@gmail.com");
            jtxtPatientNHS.setText("49589454");
            jtxtEMIS.setText("646564");
            jtxtGp.setText("Yes");
        }
        
        else if (jcmbDoctorRef.getSelectedItem().equals("PM11362"))
        {
            jtxtDoctorNHS.setText("DrNHS7696");
            jtxtFirstname.setText("Fatma");
            jtxtSurname.setText("Lily");
            jtxtMedicalCentreName.setText("Deryk Cheed Medical Centre");
            jtxtPatient.setText("6754388");
            jtxtAddressCentre.setText("10 Roadwork Lane");
            jtxtPostCode.setText("908100");

            jtxtMedicalCentreRef.setText("MCR68945");
            jtxtOffice1.setText("0704674245");
            jtxtOffice2.setText("0704875654");
            jtxtFaxNo.setText("0704378543");
            jtxtEmailAddress.setText("fatmalily@gmail.com");
            jtxtPatientNHS.setText("59589454");
            jtxtEMIS.setText("646564");
            jtxtGp.setText("Yes");
        }
        else if (jcmbDoctorRef.getSelectedItem().equals("BQ01968"))
        {
            jtxtDoctorNHS.setText("DrNHS9390");
            jtxtFirstname.setText("Musa");
            jtxtSurname.setText("Raun");
            jtxtMedicalCentreName.setText("Deryk Cheed Medical Centre");
            jtxtPatient.setText("56780063");
            jtxtAddressCentre.setText("10 Roadwork Lane");
            jtxtPostCode.setText("908100");

            jtxtMedicalCentreRef.setText("MCR68945");
            jtxtOffice1.setText("0704350567");
            jtxtOffice2.setText("0704350457");
            jtxtFaxNo.setText("0704355453");
            jtxtEmailAddress.setText("musaraun@gmail.com");
            jtxtPatientNHS.setText("49589454");
            jtxtEMIS.setText("646564");
            jtxtGp.setText("Yes");
        }        
    }//GEN-LAST:event_jcmbDoctorRefActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnHospital;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnPharmacyoffice;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JComboBox<String> jcmbDoctorRef;
    private javax.swing.JComboBox<String> jcmbNameTablets;
    private javax.swing.JButton jtnExit;
    private javax.swing.JTextField jtxtAddressCentre;
    private javax.swing.JTextField jtxtDoctorNHS;
    private javax.swing.JTextField jtxtEMIS;
    private javax.swing.JTextField jtxtEmailAddress;
    private javax.swing.JTextField jtxtFaxNo;
    private javax.swing.JTextField jtxtFirstname;
    private javax.swing.JTextField jtxtGp;
    private javax.swing.JTextField jtxtMedicalCentreName;
    private javax.swing.JTextField jtxtMedicalCentreRef;
    private javax.swing.JTextField jtxtOffice1;
    private javax.swing.JTextField jtxtOffice2;
    private javax.swing.JTextField jtxtPatient;
    private javax.swing.JTextField jtxtPatientNHS;
    private javax.swing.JTextField jtxtPostCode;
    private javax.swing.JTextArea jtxtPrescription;
    private javax.swing.JTextField jtxtSurname;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
